name: Build Spring Boot Application and Upload Artifact

on:
  push:
    branches:
      - main # main 브랜치에 푸시될 때 워크플로우 실행
  pull_request:
    branches:
      - main # main 브랜치로 풀 리퀘스트가 생성될 때 워크플로우 실행

jobs:
  build:
    runs-on: ubuntu-latest # Ubuntu 최신 버전에서 빌드 실행

    steps:
      - name: Checkout code # GitHub 레포지토리 코드 체크아웃
        uses: actions/checkout@v4

      - name: Set up JDK 17 # JDK 17 설정 (프로젝트 JDK 버전에 맞게 변경)
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin' # AdoptOpenJDK 또는 Temurin과 같은 배포판 지정
          cache: 'gradle' # Gradle 캐싱 활성화 (빌드 속도 향상)

      - name: Grant execute permission for gradlew # gradlew 실행 권한 부여
        run: chmod +x gradlew

      - name: Build with Gradle # Gradle을 사용하여 프로젝트 빌드
        run: ./gradlew build -x test # 테스트를 건너뛰려면 -x test 추가 (선택 사항)

      # - name: Run tests # 테스트를 실행하려면 이 주석을 해제
      #   run: ./gradlew test

      - name: Upload artifact # 빌드된 JAR 파일을 아티팩트로 업로드
        uses: actions/upload-artifact@v4
        with:
          name: quillproj # 아티팩트 이름
          path: build/libs/*.jar # 빌드된 JAR 파일 경로 (프로젝트 설정에 따라 변경)
          retention-days: 90 # 아티팩트 보관 기간 (선택 사항, 기본값 90일)